#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0
"""Generate the measured Boltz-2 affinity coverage report card from public data.

Usage::

    uv run python scripts/run_affinity_coverage.py

Downloads (and caches under ~/.cache/driftset) the public ChEMBL-derived Boltz-2
benchmark (Zenodo DOI 10.5281/zenodo.18669539, CC-BY-4.0), then writes
``reports/affinity_coverage.json`` and ``reports/PROVENANCE.md``. CPU-only,
no GPU, a few seconds. Re-running with the same seed reproduces the numbers.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from driftset.adapters.affinity import boltz2_affinity_adapter
from driftset.datasets import zenodo_affinity as zaff
from driftset.decision.report import compute_coverage_report

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"
CONFIDENCES = (0.80, 0.90, 0.95)
SEED = 20260527
CAL_FRACTION = 0.5


def main() -> None:
    frame = zaff.load()
    adapter = boltz2_affinity_adapter()

    rng = np.random.default_rng(SEED)
    order = rng.permutation(len(frame))
    n_cal = int(len(frame) * CAL_FRACTION)
    cal = frame.iloc[order[:n_cal]].reset_index(drop=True)
    test = frame.iloc[order[n_cal:]].reset_index(drop=True)

    reports = [compute_coverage_report(adapter, cal, test, confidence=c) for c in CONFIDENCES]
    split_info: dict[str, object] = {
        "seed": SEED,
        "cal_fraction": CAL_FRACTION,
        "n_calibration": int(len(cal)),
        "n_test": int(len(test)),
        "scheme": "random iid split (exchangeable; split-conformal guarantee holds)",
    }
    payload: dict[str, object] = {
        "dataset": zaff.provenance(frame),
        "split": split_info,
        "naive_baseline": (
            "parametric Gaussian y_hat +/- z*std(residual_cal), contrasted with "
            "distribution-free split conformal on identical calibration data"
        ),
        "reports": [r.to_dict() for r in reports],
    }

    REPORTS_DIR.mkdir(exist_ok=True)
    (REPORTS_DIR / "affinity_coverage.json").write_text(json.dumps(payload, indent=2) + "\n")
    _write_provenance(zaff.provenance(frame), split_info, reports)

    print("Wrote reports/affinity_coverage.json and reports/PROVENANCE.md")
    for r in reports:
        print(
            f"  conf={r.confidence:.2f}  conformal={r.empirical_coverage:.4f}  "
            f"naive={r.naive_coverage:.4f}  width={r.mean_interval_width:.3f}"
        )


def _write_provenance(prov: dict, split: dict, reports: list) -> None:
    lines = [
        "<!-- Generated by scripts/run_affinity_coverage.py — do not edit by hand. -->",
        "# Affinity coverage — data provenance",
        "",
        f"- **Dataset**: {prov['file']}",
        f"- **DOI**: {prov['doi']}",
        f"- **URL**: {prov['url']}",
        f"- **License**: {prov['license']}",
        f"- **SHA-256**: `{prov['sha256']}`",
        f"- **Prediction column**: `{prov['prediction_column']}` (Boltz-2)",
        f"- **Ground-truth column**: `{prov['truth_column']}` (experimental pChEMBL)",
        f"- **Rows used** (non-null pred & truth): {prov.get('n_rows_used')}",
        "",
        "## Reproduce",
        "",
        "```bash",
        "uv sync --extra dev",
        "uv run python scripts/run_affinity_coverage.py",
        "```",
        "",
        f"Random iid split, seed `{split['seed']}`, "
        f"cal_fraction `{split['cal_fraction']}` "
        f"(n_cal={split['n_calibration']}, n_test={split['n_test']}).",
        "",
        "## Measured coverage",
        "",
        "| Target | Conformal coverage | Naive-Gaussian coverage | Conformal width |",
        "|---|---|---|---|",
    ]
    for r in reports:
        lines.append(
            f"| {r.confidence:.2f} | {r.empirical_coverage:.4f} | "
            f"{r.naive_coverage:.4f} | {r.mean_interval_width:.3f} |"
        )
    lines.append("")
    (REPORTS_DIR / "PROVENANCE.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
